### ISSUE TITLE
Changing presentation-default-text-scale has no effect

### ISSUE THREAD

**Issue by dieggsy** [zonuexe/emacs-presentation-mode#2]
1. `M-x presentation-mode`
2. Once more to turn it off
3. `M-: (setq presentation-default-text-scale 2)` 
4. `M-x presentation-mode`

Scale is unchanged

**Comment by zonuexe** [comment]
@dieggsy 
Yes, it is a behavior designed as specified in the README. However, I also understood that some people do not like its behavior, so I improved it.

You should choose either **A** or **B**.

 * **A**: Put `(setq-default presentation-keep-last-text-scale nil)` in your `.emacs` (`init.el`) file.
 * **B**: `M-: (setq presentation-last-text-scale 2)` instead of `presentation-default-text-scale`

This is possible with the latest version of presentation.

**Comment by dieggsy** [comment]
@zonuexe The readme only mentions presentation-default-text-scale with regard to behavior across sessions, not across calls to `presentation-mode`, so I'd say that's fairly unclear?

And thanks for the change, but it feels pretty unintuitive to be changing this behavior with regard to "last" behavior instead of "default" behavior (i.e. just namewise, it feels wrong to set `presentation-last-text-scale`)

I actually hadn't seen the `C-x C-+` / `C-x C--` bit though, so I suppose that's fine.
